version: '2'
services:
  pantry:
    stdin_open: true
    tty: true
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      ENVIRONMENT: development
      JWT_SECRET: password
      MYSQL_HOST: mysql
      MYSQL_DATABASE: pantry
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      LOG_HOST: fluentd
      LOG_PORT: 24224
    networks:
      - codejetnet
  mysql:
      image: mariadb:10.2
      ports:
        - 3306:3306
      expose:
        - 3306
      environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: pantry
      volumes:
        - pantrydb:/var/lib/mysql
      networks:
        - codejetnet
  fluentd:
      image: fluent/fluentd
      expose:
        - 24224
      volumes:
        - ../logs:/fluentd/log
      networks:
        - codejetnet
volumes:
  pantrydb:
    driver: local
networks:
  codejetnet:
    driver: "bridge"